apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      volumes:
          - name: grafana-pv
            persistentVolumeClaim:
              claimName: grafana-pvc
          - name: grafana-storage
            emptyDir: {}
          - name: grafana-datasources
            configMap:
              defaultMode: 420
              name: grafana-datasources

      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grafana
              containerPort: 3000
          resources:
            limits:
              memory: '1Gi'
              cpu: '1000m'
            requests:
              memory: 500M
              cpu: '500m'
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
            - mountPath: /var/lib/grafana
              name: grafana-pv
          env:
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: 'true'
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: 'true'
            - name: GF_AUTH_ANONYMOUS_ORG_NAME
              value: default
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: 'false'
            - name: GF_AUTH_DISABLE_LOGIN
              value: 'false'
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
    
            
      