apiVersion: v1
kind: Service
metadata:
  name: klusterview
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: klusterview
  type: {{ .Values.service.type }}
  ports:
    - name: prod
      port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: 31001
      protocol: TCP
